spring:
    application:
        name: projeto-web
    datasource:
        driver-class-name: org.postgresql.Driver
        url: "jdbc:postgresql://localhost:5432/projetoweb"
        username: "${DB_USER:postgres}"
        password: "${DB_PASSWORD}"
    flyway:
        enabled: true
        baseline-on-migrate: true
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true